# Site settings
name: Adil Modan
title: Adil Modan | FinTech Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://adilmodan.github.io/
baseurl: ''
email: adilmodan@gmail.com
cover: https://adilmodan.github.io/img/og.png
logo: https://adilmodan.github.io/img/emojis/technologist.png
resume: https://adilmodan.github.io/resume.pdf
social:
  - title: email
    url: mailto:adilmodan@gmail.com
  - title: twitter
    url: https://twitter.com/adilmodan
  - title: instagram
    url: https://instagram.com/adillions
  - title: github
    url: https://github.com/adilmodan
  - title: linkedin
    url: https://www.linkedin.com/in/adilmodan

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
